CREATE TABLE harvest_table_listings (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    date_modified TIMESTAMP DEFAULT now() NOT NULL,
    img_location TEXT,
    location TEXT NOT NULL,
    lat DECIMAL(20,15) NOT NULL,
    lng DECIMAL(20,15) NOT NULL,
    description TEXT,
    user_id INTEGER
        REFERENCES harvest_table_users(id) ON DELETE CASCADE NOT NULL
);